Update the uapi/sound/asound.h to mitigate errors
---
Since I (EncryptedCicada) don't know how to properly give credit I am
leaving the following:
---

The uapi header asound.h defines types based on struct timespec. We need
to #include <time.h> to get access to the definition of this struct.

Previously, we encountered the following error message when building
applications with a clang/bionic toolchain:

kernel-headers/sound/asound.h:350:19: error: field has incomplete type 'struct timespec'
  struct timespec trigger_tstamp;
                  ^

The absence of the time.h #include statement does not cause build errors
with glibc, because its version of stdlib.h indirectly includes time.h.

Signed-off-by: Daniel Mentz <danielmentz@google.com>
---
 include/uapi/sound/asound.h | 1 +
 1 file changed, 1 insertion(+)